### PR TITLE
big file download fix

### PR DESCRIPTION
**Pull request by bojanvu23**
changing code used for downloading file with function from Apache
Commons library

issue #57

### CODE REVIEW

**Comment by jogrimst** [comment]
@bojanvu23 Can you include the issue number in the pull request, so that we can see which GitHub issue the pull request is for?

**Comment by bojanvu23** [comment]
@jogrimst 
Changes are tested using Android Studio memory monitor during downloading 500MB file.
New code downloaded file successfully, while previous code causes java.lang.OutOfMemoryError.

**Comment by bojanvu23** [comment]
@jogrimst yes, and during all download process memory consumption was constant.

**Comment by jogrimst** [comment]
> yes, and during all download process memory consumption was constant.

So can we remove `android:largeHeap="true"` also? Can you add the removal to the pull request?

**Comment by bojanvu23** [comment]
Hi @jogrimst ,

We can do it.

OK, I'm going to remove it.

**Comment by bojanvu23** [comment]
property largeheap is removed

**Comment by bojanvu23** [comment]
There won't be problem, in meanwhile I tested it with device which has 512MB ram and everything works perfectly.

**Pull request merged**
